### ISSUE TITLE
Can't include in more than one T.U., due to only one method being declared inline

### ISSUE THREAD

**Issue by abigagli** [adishavit/argh#13]
Any reason why only `void parser::parse(const char * const argv[], int mode)` is defined `inline`?
I know it might not be the common use case, but I'd need to include argh.h in multiple TUs, and this is causing multiple definitions error while linking. 

Am I missing something?

**Comment by adishavit** [comment]
Good catch, I guess it never came up since `main()` is always defined in a single TU and that's only where `argh` is typically `#include`d.
You can/should add the `inline`s and send a PR. 
LMK if  you are having problems with this and I'll do it.

**Comment by abigagli** [comment]
No problem. PR completed

**Comment by adishavit** [comment]
Cool - thanks!

I wonder, what's your use-case for including in 2 TUs?

**Comment by abigagli** [comment]
Well, I have refactored a "test-driver" application that can operate in several different modes (depending on the thing it has to test) so that main is now just a dispatcher to various testing functions. So main has to first look at the command line to get some general flags and check which "mode" the user want the application to run. Depending on that, it will invoke one of the several different functions coming from different TUs, but each function will have to dissect the remaining part of the command line for its own function-specific arguments.
Hope that makes sense...

**Comment by adishavit** [comment]
Makes sense - thanks!
🙂
