### ISSUE TITLE
Conan package for Argh

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [adishavit/argh#18]
Hello, i created Conan recipe for your library.

https://github.com/bincrafters/conan-argh/tree/testing/1.2.0

**Comment by adishavit** [comment]
Fantastic! 
Can you add a comment with link and simple usage instructions to the readme?

**Comment by danimtb** [comment]
Hi @ZaMaZaN4iK

I have submitted a PR #19 based on your great work asking for official support of argh! in conan-center.

@adishavit, I have also detailed the steps to create the package and upload it 😄
