### ISSUE TITLE
Support multiple names per option

### ISSUE THREAD

**Issue by adishavit** [adishavit/argh#2]
Add ability to specify multiple strings per option: `-v`/`--verbose`.

**Comment by adishavit** [comment]
[Inspired by Clara](https://github.com/philsquared/Catch/blob/master/include/internal/catch_commandline.hpp#L98), one way to do it is via optional multiple `[]` or `()` calls.

**Comment by philsquared** [comment]
you're welcome :-)

**Comment by adishavit** [comment]
I opted for using initializer-lists instead.
It was simpler to implement and less open to abuse.
The following is now valid:
```
if (cmdl[{ "?", "h", "help"}]) // chain alternatives
   show_usage(); 
```

**Comment by philsquared** [comment]
That seems like the right choice for what you want from it.
