### ISSUE TITLE
Check if value of option is X

### ISSUE THREAD

**Issue by redorav** [adishavit/argh#20]
I don't know argh enough to say whether this is possible or not, but I would like do something like the following:

if(commandLine["-option", "value"])
{
   // do something
}

At the moment I need to do something like:

if(commandLine("-option").str().compare("value") == 0)
{
    // do something
}

It's not a lot, of course, but say you wanted to OR them or AND them or you have a long sequence of ifs

Is this possible? Thanks!

**Comment by adishavit** [comment]
The Argh parser does not know the type of the value you expect. 
You _can_ compare the argument _string_:
```
if("value" == commandLine("-option").str())
{
   // do something
}
```
For types other than `std::string` you need to perform the type conversion on your end.
In C++17:
```
if(int v=-1; (commandLine("-option") >> v) && value == v)
{
   // do something
}
```
This uses C++17 "if statements with initializers".
It also handles the two failure cases where `"-option"` was not specified on the command line, or that the conversion failed (e.g. passing `"foo"` for something expecting an `int`).

**Comment by redorav** [comment]
Ah, my bad, of course. I think I have this concept of "don't compare a const char* to another const char* via ==" so ingrained that I end up applying the same to std::string.

This

if(commandLine("-option") == "value")
{

}

works just fine and is concise and good, thanks for taking the time to answer.
