### ISSUE TITLE
Case insensitivity mode

### ISSUE THREAD

**Issue by isRyven** [adishavit/argh#22]
Hi, thank you for your amazing work! 
I wonder if you could add a mode to enable cases insensitivity for option/flag name matching?
Sure, i could manually preprocess arguments beforehand, but that would require to make my own flag parser and then apply case transformations, which is something i don't want to bother with.
I just wonder if something like `CASE_INSENSITIVE_FLAG_MATCH` could be added, this would be really important feature for my project. This would just transform any flag name into lower cased one on parsing and store it, but the operators don't have to bother doing transformations, it would expect you to always enter lower cased names to decrease the complexity.

The lower cased transformation could be something as simple as:
```cpp
std::transform(s.begin(), s.end(), s.begin(), [](unsigned char c) { return std::tolower(c) });
```
which is completely in bounds of std libs and c++11 requirements.

**Comment by adishavit** [comment]
Interesting. I’m traveling now so I won’t get around to this for a couple of weeks. 
Until I get a chance to review this, you can apply something very similar to you snippet directly to all `argv` elements before you pass it for parsing.

**Comment by adishavit** [comment]
Ah, I understand what you mean now. You’re right. 
You _could_ try to add this functionality yourself and send a PR...

**Comment by adishavit** [comment]
Argh tries to leave a lot of the decisions to the user (e.g. type conversions).
Even though argh is ASCII based, on some platforms the options may be in a foreign language and a simple internal `tolower()` may not suffice. 

Another design decision is whether to change the input option case to lower, thus losing the original input values, or doing it at the string match level. Although the latter is more work, I prefer it since the user retains the ability to access the original values.  

I will think about this.

**Comment by isRyven** [comment]
My current solution would be to call `lowercase_option` function right after the trim is done:
```cpp
auto name = trim_leading_dashes(args_[i]);

if (mode & CASE_INSENSITIVE_OPTION_MATCH) {
       name = lowercase_option(name);
}
```
```cpp
inline std::string parser::lowercase_option(std::string const &option) const
{
      auto lowOpt = option;
      auto end = lowOpt.end();
      auto equalPos = option.find('=');
      if (equalPos != std::string::npos) {
            end = lowOpt.begin() + equalPos;
      }
      std::transform(lowOpt.begin(), end, lowOpt.begin(), [](unsigned char c) { 
            return std::tolower(c);
      });
      return lowOpt;
}
```
It could take the name as reference and modify the original string, but i decided to adhere to a const string argument instead. And the `lowercase_option` would also handle the option with equal sign, to make sure its argument would stay untouched.

This works great for the cases i need. But yeah i am not sure how to handle utf8 or such, and since i thought argh is ascii driven anyways, using tolower would be sufficient.

**Comment by isRyven** [comment]
But yeah you will lose the original option names. But i wonder if that's an issue. 🤔
You would barely want to access them through index anyways. And non-option arguments would still stay untouched. So there should not be any big problem with that, in my opinion. 
But you might be right that it should be handled on a match level, since then you can use original names for some information printing.

**Comment by isRyven** [comment]
Also consider this, i have to check hundreds of options, but only few of them most of the time will be set, it makes sense to transform them upon parsing just for the performance sake.

**Comment by adishavit** [comment]
Interesting point. I wonder how common case-insensitive options are.

**Comment by isRyven** [comment]
Yeah i don't know, but, for instance, this is mostly useful if you have multi-worded options like these,
`-verboseentities`, `-rawlightmapsizelimit`, `-samplessearchboxsize` or `-gridambientdirectionality`,
which i could just define all camel cased, if only they wouldn't be established and defined many years ago.

But then you also have some other flags that are defined using mixed case,
`-sRGBlight`, `-sRGBtex`, `-sRGBcolor`.

And as you can see, it just happens, that the naming doesn't follow any system, which makes people to think there is no difference in how you enter these options, especially when you have a lot of them. 

I would want to bring a system and readable in naming, so i could keep them nicely camel cased in docs and help print, which isn't atm, but yet allow people to enter them in what ever case they want, if that makes sense.

I am really happy to use your little lib, makes things much cleaner and readable, just need that one little switch, to make it even more comfortable.

**Comment by adishavit** [comment]
I think the two alternatives are more or less orthogonal. We could have the option to lowercase the input flags upon parsing. That will set you up as you want. 
If anyone wants case-insensitive matching, that could hypothetically be added later when the request comes.

**Comment by adishavit** [comment]
I think there are too many subtle sharp edges here with e.g. retaining original input values (e.g. for error messages) or avoiding lower casing values in strings things like `--arg=val`, duplicate casings are treated as unique flags etc.
You can always use Argh to parse your flags/params and create your own case-map map for the actual values.
