### ISSUE TITLE
Multiple params with the same name?

### ISSUE THREAD

**Issue by braddabug** [adishavit/argh#36]
Is it possible to do something like this:

myprogram -p foo -p bar -p baz

and be able to get all three -p parameter values? When I try I can only get the first one.

**Comment by adishavit** [comment]
You could try changing the internal `std::map` to `std::multimap` and use the `params()` method to access all the values. The normal minimal interface will fetch just one parameter (not sure which).

I'll have to think if this is a desired default behavior (instead of overwriting).

**Comment by biocodz** [comment]
Using repeated parameters is a very valid use case, and e.g.  Gnu `getopt` handles it by default. `GFlags` doesn't handle repeated flags, which was a show-stopper in my case. 
Changing `map` to `multimap` indeed solves this in a snap. Why the doubts?

**Comment by joeroback** [comment]
yea, trying to achieve the same thing.. also found it odd that the first instance was the value, not the last

**Comment by adishavit** [comment]
Hmmm.. if you expect them in order then a simple multimap would not suffice. I’d need to store the index too.

**Comment by yuvalif** [comment]
this may also be useful for the case where I want to use multiple boolean parameter with the same name. e.g. `-vvv` for "3 times verbose execution" of the program.

**Comment by adishavit** [comment]
I think the `-vvv` example is different.  
I think the upper bound is always a small finite number. Just keep/handle every sequence as a unique parameter (`-v`, `-vv`, `-vvv`...). 
I doubt you will get to even 10 repetitions (and certainly it would not be a common use case).

**Comment by yuvalif** [comment]
that would work, but note that in getopt `-vv` is the same as `-v -v` 
this is why the single dash and a double dash

**Comment by adishavit** [comment]
In any case, the original issue was about repeated **_value_** params (`-p=foo -p=bar -p=baz`) and you are asking about flags (which are just always a boolean `True` by mere appearance) so there is no "value" to store in the map or multimap anyway.

**Comment by redorav** [comment]
For my use case, I am trying to use argh in a custom compiler and need to parse -D for defines, and setting multiple defines is normally quite easy when using -D DEFINE1 -D DEFINE2 Currently I don't think I can do it
