### ISSUE TITLE
Is there a way I can use ``-k value`` like numerous command line tools?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [adishavit/argh#37]

**Comment by adishavit** [comment]
Argh is a library for handling command line arguments like that. I don’t understand your question. You will have to be more specific about you want. Maybe read the docs and give an example.

**Comment by ThatNerdyPikachu** [comment]
Instead of -k=v, which seems to be the default, I want to be able to pass -key value instead

**Comment by adishavit** [comment]
Ah, of course it’s supported. 
You either have to pre-register `k` as a parameter or set the default options to be parameters and not flags by default.

**Comment by adishavit** [comment]
Funnily enough, it is the `-k=v` syntax that is the lazy/minimalist shortcut and was only added after the library was first created.

**Comment by ThatNerdyPikachu** [comment]
Heh.

How would I register it, I think I’m missing something in the docs.. (sorry)

**Comment by adishavit** [comment]
Search the readme for PREFER_PARAM_FOR_UNREG_OPTION` for defaulting and for `add_param()`. They are consecutive and explain both options with examples. 

The section starts with:
> “By default, options are assumed to be boolean flags. When this is not what you want, there are several ways to specify when an option is a parameter with an associated value...”

**Comment by ThatNerdyPikachu** [comment]
Thanks!!
