### ISSUE TITLE
Add a documentation to a parameter?

### ISSUE THREAD

**Issue by dcoeurjo** [adishavit/argh#39]
Nice project ! 

Is there a way to specify a short description of a parameter (which could be used to generate a kind of `-h`) ?

**Comment by adishavit** [comment]
Not at the moment. Argh is eager and minimal and does not currently automatically generate a usage message. 

It is a feature I am considering but not at the cost of added complexity. I may add something like that with C++20 NTTP but that’s still experimental and in the future.

**Comment by dcoeurjo** [comment]
👌 thx
