### ISSUE TITLE
Multiple Parameters for 1 Argument

### ISSUE THREAD

**Issue by derens99** [adishavit/argh#45]
Hello,
I'm wondering if this great library has the functionality of entering multiple parameters for 1 argument. An example would be --arrayOf4 1 2 3 4. Then, I could get these 4 numbers and put them into an array. Is this already a feature in this library? If so, could I get a pointer on achieving that goal?
Thanks

**Comment by adishavit** [comment]
Unfortunately that’s not possible.
A workaround might be to use:
`—arrayOf4=1,2,3,4` with no spaces and parse it yourself...
