### ISSUE TITLE
Problem space in string value 

### ISSUE THREAD

**Issue by rere-rere** [adishavit/argh#50]
Hello, 

I would like to put  string value with space. Currently I could have only the first element. 
Example :

`my-app --config="test test"`

I have :
`test`

Here is the code I used : 
```

  argh::parser cmdl;
  cmdl.add_params({"-t", "--config", "-s", "--scale"});
  cmdl.parse(argc, argv);
  std::cout << cmdl("config").str() << '\n';
```
I don't know if someone already handle this problem ?

Best regards

**Comment by adishavit** [comment]
Hmmm... the last tip in the readme Tips section shows exactly this example 🤔. 
I’ll check.

**Comment by rere-rere** [comment]
Ok, I found what was the problem it was my mistake.
I have an intermediary script for running my program to Docker.
Sorry about that, and thanks for the help.

Best regards
