### ISSUE TITLE
Add support of compound arguments

### ISSUE THREAD

**Issue by ivan-volnov** [adishavit/argh#52]
Compound arguments are optional arguments that are combined and provided as a single argument. Example: ps -aux

**Comment by adishavit** [comment]
This is already supported via the  `SINGLE_DASH_IS_MULTIFLAG` parsing mode. 🙂

**Comment by ivan-volnov** [comment]
Wow, thank you very much for such a great library!

**Comment by adishavit** [comment]
I added the term "compound arguments" to the readme for improved search. Thanks.
