### ISSUE TITLE
The best way to check for unrecognised param to show help message?

### ISSUE THREAD

**Issue by ivan-volnov** [adishavit/argh#53]
Subj.

Thanks!

**Comment by adishavit** [comment]
Argh parses whatever arguments are provided. It’s up to the user to decide what they mean and how they are used. 
It is not design to limit the acceptable values. 
One way you may achieve what you want is to (externally) iterate over all the given flags and parameters and check if they belong to your user defined “known” set. If not issue your help message.

**Comment by ivan-volnov** [comment]
Thanks.
