### ISSUE TITLE
API: Consider not including argv[0] in pos_args

### ISSUE THREAD

**Issue by woodruffw** [adishavit/argh#57]
Hey there! Thanks a ton for creating and maintaining `argh`, it's a pleasure to use.

I'm currently using it to rewrite one of my company's CLI tools, and I noticed that both the default iterator *and* `pos_args()` both include `argv[0]` (i.e., typically the executable path) in the positional argument iterator.

IMO, this should **not** be included, at least for `pos_args()`:

* As far as I know, it's not common to refer to `argv[0]` as a positional argument. The main context where I'm aware of `argv[0]` being treated as a normal positional is shell programming, but special meta-arguments like `$*` and `$@` don't include it.
* Including `argv[0]` in `pos_args()` makes at least one intuitive use of `argh` more difficult than it needs to be. Consider the following use for a program whose CLI looks like `whatever [flags] <file1 [file2 ...]>`:

    ```c++
    {
      argh::parser cmdl(argc, argv);
      
      // ... flag parsing ...
      
      // sanity check: exit unless we have at least one positional
      if (cmdl.size() < 2) { ... }
      
      for (auto &pos : cmdl) {
        // BOOM: first pos here is argv[0], which we probably didn't mean to process
        process(pos);
      }
    }
    ```

    The above would ideally work, but doesn't with the current default iterator or `pos_args()` iterator.

As a solution, I propose the following changes:

* Retain the current `size()` and default iterator APIs without changes
* Add a `pos_size()` API that should always be **just** the positional count without `argv[0]`, and modify the `pos_args()` iterator to not emit `argv[0]`

Let me know what you think! I'm also happy to take a stab at implementing these changes.

**Comment by adishavit** [comment]
I'm glad that you are enjoying Argh! - thanks for your kind words.

I frequently use `argv[0]`. It is especially useful when writing usage instructions or when you need the actual running path of the executable. I do not think the library needs to change or remove some of the available data.

That being said, you may always just pass `argv+1` to Argh! (instead of just `argv` and correspondingly passing `argc-1` too) .

```
argh::parser cmdl(argc-1, argv+1); // skip first argument: executable full path
```
This will skip the first argument as you desire for your own use cases.

**Comment by woodruffw** [comment]
Thanks for the response!

Looking again, just using `argv + 1` is obvious -- not sure why that didn't occur to me 😅.

I agree that having `argv[0]` available *is* useful, but I'm content to disagree about whether it belongs in a "positional arguments" API. In any case, thanks again!
