### ISSUE TITLE
Conan center mark argh! as deprecated

### ISSUE THREAD

**Issue by jtorresfabra** [adishavit/argh#59]
Hi @adishavit,

Wanted to give a try and saw that conan center is marking this as deprecated https://conan.io/center/argh?os=&tab=configuration. 
Not sure if is an issue in the conanfile.py configuration or something. 

Thanks!

**Comment by a4z** [comment]
I created a PR in cci, see https://github.com/conan-io/conan-center-index/pull/5358, so it should soon be back there

**Comment by jtorresfabra** [comment]
Thanks! waiting for them to merge to close the issue, don't hesitate to close it yourself if you feel is better to do it right now.

**Comment by a4z** [comment]
@adishavit , you can close that issue, argh is again on cci 
https://conan.io/center/argh

**Comment by jtorresfabra** [comment]
@a4z Thanks for your quick fix! I'm closing it.
