### ISSUE TITLE
question: Several arguments for a param support

### ISSUE THREAD

**Issue by jtorresfabra** [adishavit/argh#60]
Is there an easy way to parse things like:

```--output outputdir --input file1 file2 file3 ```

I need several values for each parameter in some cases, and cannot know in advance the position of each argument.

**Comment by adishavit** [comment]
No. Not really. With that precise syntax not without trying to outsmart
argh.
That would probably make you write almost as much code as you would writing
it yourself.

I haven't tried this, but if you don't mind a small syntax change, you
could add a *non-space* separator between them or "quotes" so they would
all parse and a single token though:
--output outputdir --input file1,file2,file3
 or
--output outputdir --input "file1 file2 file3"
 or
--output outputdir --input=file1,file2,file3

Let me know if that works.

**Comment by jtorresfabra** [comment]
Yep that works well enough for my needs. Thanks!

**Comment by adishavit** [comment]
Great!
Which of the suggested versions works for you?

**Comment by jtorresfabra** [comment]
I just tried `--input file1,file2,file3`, then I split the string myself, everything good.
