### ISSUE TITLE
parse() should be idempotent

### ISSUE THREAD

**Issue by lunakid** [adishavit/argh#68]
Calling `parse()` multiple times on the same input should yield the same result every time.
Currently it appends the extracted inputs to the positional results (vector) anew, instead of replacing them. (Didn't check other cases.)
_(Not that it's a common case of course, but a nice-to-have correctness safeguard; one less thing to worry about with this lovely little package.)_

Just reset the affected container(s) at the beginning of `parse()`.

**Comment by lunakid** [comment]
(Strictly speaking, this is not just an idempotency issue, as it leads to incorrect(ly accumulating) results for _different_ inputs, too (for the same instance). But I'm not very familiar with the Argh! API, my understanding is tentative.)

**Comment by adishavit** [comment]
Good idea. Can you make the change, write some unit test and make a PR? 😊🙏

**Comment by lunakid** [comment]
I'm afraid I'll have to leave this exercise to others, as my capacity for this contribution has been exhausted. :) (I just added a static guard to the `parse()` call in my code. ;) )
