### ISSUE TITLE
Quoted string containing spaces is only read up to the first space. 

### ISSUE THREAD

**Issue by DanielKrawisz** [adishavit/argh#84]
When I enter in a quoted string containing spaces into the command line and try to read it as a positional argument, argh::parser only reads it up to the first space. How do I get the whole string?

**Comment by DanielKrawisz** [comment]
Hi, I realized that the real problem is actually that if you read a string from a stringstream with >> it will stop at the first space.

**Comment by adishavit** [comment]
Yes. This is also mention in the **Tips** section of the readme:

> When parsing parameter values as strings that may contain spaces (e.g. --config="C:\Folder\With Space\Config.ini"), prefer using .str() instead of >> to avoid the default automatic whitespace input stream tokenization:
cout << cmdl({ "-c", "--config" }).str().
